name: Continuous Integration

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set version environment variable
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('C_VERSION', context.ref.substring(10).replace('v', ''))
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cmingly/qbittorrent:latest,cmingly/qbittorrent:${{ env.C_VERSION }}
